//
//  LibreAccessServiceSvc+Binding.h
//  Scholastic
//
//  Created by John Eddie on 27/03/2012.
//  Copyright (c) 2012 BitWink. All rights reserved.
//

#import "LibreAccessServiceSvc.h"

// Re-define some elements of the generated web service to ease any WSDL changes

typedef LibreAccessService_1_2_0Soap11Binding LibreAccessServiceSoap11Binding;
typedef LibreAccessService_1_2_0Soap11BindingOperation LibreAccessServiceSoap11BindingOperation;
typedef LibreAccessService_1_2_0Soap11BindingResponse LibreAccessServiceSoap11BindingResponse;

@protocol LibreAccessServiceSoap11BindingResponseDelegate <LibreAccessService_1_2_0Soap11BindingResponseDelegate>
@end

typedef LibreAccessService_1_2_0Soap11Binding_TokenExchange LibreAccessServiceSoap11Binding_TokenExchange;
typedef LibreAccessService_1_2_0Soap11Binding_AuthenticateDevice LibreAccessServiceSoap11Binding_AuthenticateDevice;
typedef LibreAccessService_1_2_0Soap11Binding_RenewToken LibreAccessServiceSoap11Binding_RenewToken;
typedef LibreAccessService_1_2_0Soap11Binding_GetUserProfiles LibreAccessServiceSoap11Binding_GetUserProfiles;
typedef LibreAccessService_1_2_0Soap11Binding_ListBooksAssignment LibreAccessServiceSoap11Binding_ListBooksAssignment;
typedef LibreAccessService_1_2_0Soap11Binding_ListContentMetadata LibreAccessServiceSoap11Binding_ListContentMetadata;
typedef LibreAccessService_1_2_0Soap11Binding_SaveUserProfiles LibreAccessServiceSoap11Binding_SaveUserProfiles;
typedef LibreAccessService_1_2_0Soap11Binding_ListUserSettings LibreAccessServiceSoap11Binding_ListUserSettings;
typedef LibreAccessService_1_2_0Soap11Binding_SaveUserSettings LibreAccessServiceSoap11Binding_SaveUserSettings;
typedef LibreAccessService_1_2_0Soap11Binding_ListProfileContentAnnotations LibreAccessServiceSoap11Binding_ListProfileContentAnnotations;
typedef LibreAccessService_1_2_0Soap11Binding_SaveProfileContentAnnotations LibreAccessServiceSoap11Binding_SaveProfileContentAnnotations;
typedef LibreAccessService_1_2_0Soap11Binding_SaveContentProfileAssignment LibreAccessService_Soap11Binding_SaveContentProfileAssignment;
typedef LibreAccessService_1_2_0Soap11Binding_SaveReadingStatisticsDetailed LibreAccessServiceSoap11Binding_SaveReadingStatisticsDetailed;
typedef LibreAccessService_1_2_0Soap11Binding_ListFavoriteTypes LibreAccessServiceSoap11Binding_ListFavoriteTypes;

@interface LibreAccessServiceSvc (Binding)

+ (LibreAccessServiceSoap11Binding *)SCHLibreAccessServiceSoap11Binding;

@end
